### ISSUE TITLE
References to Places() object

### ISSUE THREAD

**Issue by dpikt** [kontrollanten/algolia-places-react#230]
It'd be nice to have a reference to the inner `Places` object if we wanted to programmatically call any of the methods or do anything fancy. (https://community.algolia.com/places/documentation.html#methods)

You could accomplish this via a ref-style prop:
```js
class OpenOnMountExample extends React.Component {
    componentDidMount () {
        if (this.placesRef) this.placesRef.open()
    }
    render () {
        return (
           <AlgoliaPlaces placesRef={ places => this.placesRef = places } ... />
        )
    }
}
```

Thoughts on this approach?

**Comment by kontrollanten** [comment]
Thanks! I think that can be a great idea! Unfortunately I don't have time in the near future to add this functionality, but you're welcome to create a PR =)

**Comment by dpikt** [comment]
Great! I'll have a colleague of mine submit a PR once we've finalized our fork.

**Comment by dharyadi** [comment]
Is there any tutorial on how to use this props?
