### ISSUE TITLE
How to change the format of address suggestions from algolia?

### ISSUE THREAD

**Issue by dharyadi** [kontrollanten/algolia-places-react#336]
Hi. Thanks for the great package.

I just want to ask how to change the  format of the suggested addresses?

For example, I want the suggestion to return street,suburb and state. At the moment, it returns street,city and state. Thanks

**Comment by kontrollanten** [comment]
Thanks! Sorry for a late reply. You can change the format via Places API, you can check the documentation here https://community.algolia.com/places/documentation.html#api-options-templates
