### ISSUE TITLE
How can I clear input field after onChange handler?

### ISSUE THREAD

**Issue by jurahalas** [kontrollanten/algolia-places-react#391]

**Comment by jurahalas** [comment]
For this we can use placeRef prop. 
for example 
placesRef={ ref => { input = ref } }

and for onChange handle call input.setVal('')

**Comment by golestanirad** [comment]
i get this error:
`this.props.placesRef is not a function`

**Comment by kontrollanten** [comment]
`placesRef` has to be a function, `placesRef={(ref) => {inputEl = ref;}}` should work.
