### ISSUE TITLE
Not working with cssClasses option of autocomplete.js

### ISSUE THREAD

**Issue by arnaudambro** [kontrollanten/algolia-places-react#7]
Hi there,

Here is my code 

        <AlgoliaPlaces 
          options={{
            apiKey:`${process.env.REACT_APP_AGOLIA_API_KEY}`,
            appId:`${process.env.REACT_APP_AGOLIA_API_ID}`,
            useDeviceLocation: true,
            autocompleteOptions: {
              autoselect: true,
              autoselectOnBlur: true,
              hint: true,
              debug: false,
              openOnFocus: false,
              cssClasses: {
              // root: 'algolia-autocomplete',
              // prefix: 'aa',
              // noPrefix: false,
              // dropdownMenu: 'dropdown-menu',
              // input: 'input',
              // hint: 'hint',
              // suggestions: 'suggestions',
              // suggestion: 'suggestion',
              // cursor: 'cursor',
              // dataset: 'dataset',
              // empty: 'empty',
              }
            },
          }}
          placeholder={this.state.placeholder}
          onChange={this.handleInputChange}
          onError={this.handleError}
        />

What I did is : when I comment the `cssClasses` option from `autocompleteOptions`, it's working fine. When I put `cssClasses`, whether its options are empty or filled up, it's bugging.

TypeError: Cannot read property 'addEventListener' of null
places
node_modules/algolia-places-react/dist/index.js:2580
  2577 |   previousQuery = query;
  2578 | };
  2579 | 
> 2580 | autocompleteContainer.querySelector('.' + prefix + '-input').addEventListener('input', inputListener);
  2581 | 
  2582 | var autocompleteIsomorphicMethods = ['open', 'close', 'getVal'];
  2583 | autocompleteIsomorphicMethods.forEach(function (methodName) {
View compiled
AlgoliaPlaces.componentDidMount
node_modules/algolia-places-react/dist/index.js:1434
  1431 | value: function componentDidMount() {
  1432 |   var _this2 = this;
  1433 | 
> 1434 |   this.autocomplete = (0, _places2.default)(_extends({}, this.props.options, {
  1435 |     container: this.autocompleteElem
  1436 |   }));
  1437 | 
View compiled
commitLifeCycles
node_modules/react-dom/cjs/react-dom.development.js:9768
  9765 |   startPhaseTimer(finishedWork, 'componentDidMount');
  9766 |   _instance2.props = finishedWork.memoizedProps;
  9767 |   _instance2.state = finishedWork.memoizedState;
> 9768 |   _instance2.componentDidMount();
  9769 |   stopPhaseTimer();
  9770 | } else {
  9771 |   var prevProps = current.memoizedProps;
View compiled
commitAllLifeCycles
node_modules/react-dom/cjs/react-dom.development.js:11439
  11436 | if (effectTag & (Update | Callback)) {
  11437 |   recordEffect();
  11438 |   var current = nextEffect.alternate;
> 11439 |   commitLifeCycles(finishedRoot, current, nextEffect, currentTime, committedExpirationTime);
  11440 | }
  11441 | 
  11442 | if (effectTag & ErrLog) {

**Comment by kontrollanten** [comment]
I've looked deeper into it now. If you set the `cssClasses.prefix` to `ap` it's working. This is a [places](https://github.com/algolia/places) issue. 

I'd guess it's this part that screwing things up:
```
  var prefix = 'ap' + (style === false ? '-nostyle' : '');

  var autocompleteOptions = _extends({
    autoselect: true,
    hint: false,
    cssClasses: {
      root: 'algolia-places' + (style === false ? '-nostyle' : ''),
      prefix: prefix
    },
    debug: process.env.NODE_ENV === 'development'
  }, userAutocompleteOptions);
```

The `prefix` var doesn't take the `cssClasses` into account, which is why only `ap` is a valid prefix.
